.TH "TCUTEST" 1 "2008-01-17" "Man Page" "Tokyo Cabinet"

.SH NAME
tcutest \- test cases of the utility API

.SH DESCRIPTION
.PP
The command `\fBtcutest\fR' is a utility for facility test and performance test.  This command is used in the following format.  `\fIrnum\fR' specifies the number of iterations.  `\fIanum\fR' specifies the initial number of elements of array.  `\fIbnum\fR' specifies the number of buckets.
.PP
.RS
.br
\fBtcutest xstr \fIrnum\fB\fR
.RS
Perform test of extensible string.
.RE
.br
\fBtcutest list \fIrnum\fB \fR[\fB\fIanum\fB\fR]\fB\fR
.RS
Perform test of array list.
.RE
.br
\fBtcutest map \fIrnum\fB \fR[\fB\fIbnum\fB\fR]\fB\fR
.RS
Perform test of hash map.
.RE
.br
\fBtcutest mdb \fIrnum\fB \fR[\fB\fIbnum\fB\fR]\fB\fR
.RS
Perform test of on-memory database.
.RE
.br
\fBtcutest misc \fIrnum\fB\fR
.RS
Perform test of miscellaneous routines.
.RE
.br
\fBtcutest wicked \fIrnum\fB\fR
.RS
Perform updating operations of list and map selected at random.
.RE
.RE
.PP
This command returns 0 on success, another on failure.

.SH SEE ALSO
.PP
.BR tcumttest (1),
.BR tcucodec (1),
.BR tcutil (3),
.BR tokyocabinet (3)
